- category: Hearing
  id: "CF-H"
  questions:
    - question: "Who lives in the sand castle under the roof?"
      answer:
        options:
          - Mace
          - Gwen
          - Cap
    - question: "Who lives in the tube up in the night?"
      answer:
        options:
          - Goof
          - Leins
          - Deen
    - question: "Who lives on the moon up in the night?"
      answer:
        options:
          - Zack
          - Carl
          - Van
    - question: "What makes every line of code work?"
      answer:
        options:
          - Grace
          - Water
          - Rest
  observations:
    - question: "How many roofs did you see?"
      answer:
        options:
          - One
          - Two
          - Several
- category: Vision
  id: "CF-V"
  questions:
    - question: "When was Tesla built?"
      answer:
        options:
          - '1'
          - '45'
          - '456'
    - question: "How many presidents does Ghana have?"
      answer:
        options:
          - One
          - Two
          - Thirty Five
    - question: "Who owns the state?"
      answer:
        options:
          - France
          - UK
          - Iraq
    - question: "What makes you tick?"
      answer:
        options:
          - Grace
          - Life
          - Stress
  observations:
    - question: "How many roofs did you see?"
      answer:
        options:
          - One
          - Two
          - Several

      

      
